Repository Banda-Media/lunchMemo, pull requests merged in 2021-01, with the labels that each got.

#144 Feat svg
  .env example
  .eslintrc.js
  .gitattributes
  .gitignore
  ARCHIVE/src/app.js
  README.md
  app/components/modules/profile/profilePanel.tsx
  app/components/modules/registration/Login.tsx
  app/components/modules/registration/RegistrationPanel.tsx
  app/components/modules/registration/SignUp.tsx
  app/hooks/AuthContext.tsx
  app/styles/custom.scss
  app/styles/main.scss
  app/styles/parts/auth.scss
  app/styles/parts/global.scss
  app/styles/parts/layout.scss
  app/styles/parts/normalize.scss
  app/styles/parts/settings.scss
  app/styles/parts/timepicker.scss
  app/styles/svg/github.svg
  app/styles/svg/twitter.svg
  app/styles/tailwind.scss
  app/types/custom.d.ts
  app/types/types.ts
  app/utils/authRedirect.ts
  app/utils/firebase/auth.ts
  app/utils/firebase/firebase.ts
  app/utils/firebase/firestore.ts
  docs/featurepeek.svg
  docs/firebase.svg
  docs/github.svg
  docs/next.svg
  docs/tailwind.svg
  docs/tsdx.svg
  docs/typescript.svg
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/auth/token.ts
  pages/api/auth/verify.ts
  pages/dashboard.tsx
  peek.yml
  tailwind.config.js
  tailwind.js
  tsconfig.json
  vercel.json
  yarn.lock
Labels: bug, enhancement

#146 Enhancement: Revised styling/refactor of components
  app/components/layouts/Footer.tsx
  app/components/layouts/Header.tsx
  app/components/layouts/Layout.tsx
  app/components/modules/profile/profilePanel.tsx
  app/components/modules/registration/Login.tsx
  app/components/modules/registration/RegistrationPanel.tsx
  app/components/modules/registration/SignUp.tsx
  app/components/modules/registration/Socials.tsx
  app/hooks/AuthContext.tsx
  app/styles/parts/global.scss
  app/styles/parts/layout.scss
  app/styles/svg/google.svg
  app/types/types.ts
  app/utils/authRedirect.ts
  app/utils/firebase/auth.ts
  app/utils/firebase/firebase.ts
  app/utils/firebase/firestore.ts
  pages/api/auth/token.ts
  pages/api/auth/verify.ts
Labels: enhancement

#168 Changed the regex expression for email validation.
  app/utils/firebase/auth.ts
Labels: bug

#184 Random background and CSS layout bugfixes: Fixes #171, Fixes #172
  app/components/layouts/Layout.tsx
  app/components/modules/main/Background.tsx
  app/styles/parts/global.scss
  postcss.config.js
  tailwind.config.js
Labels: bug, enhancement

#188 Added mobile responsiveness to create group: Fixes #187
  app/components/modules/dashboard/components/CreateGroup.tsx
  tailwind.config.js
Labels: bug, enhancement

#192 [FEAT] Group Join/Leave + CSS Fixes: Fixes #177, Fixes #176, Fixes #173
  README.md
  app/components/common/NotificationBar.tsx
  app/components/common/forms/EmailInput.tsx
  app/components/common/forms/SubmitButton.tsx
  app/components/common/forms/TimePicker.tsx
  app/components/modules/dashboard/components/AttendeesList.tsx
  app/components/modules/dashboard/components/CreateGroup.tsx
  app/components/modules/dashboard/components/GroupButton.tsx
  app/components/modules/dashboard/components/JoinButton.tsx
  app/components/modules/dashboard/components/LunchGroup.tsx
  app/components/modules/main/Background.tsx
  app/components/modules/main/Footer/MakerLink.tsx
  app/components/modules/main/Footer/Makers.tsx
  app/components/modules/main/Footer/Newsletter.tsx
  app/components/modules/main/Header/Header.tsx
  app/components/modules/registration/Forgot.tsx
  app/components/modules/registration/Login.tsx
  app/components/modules/registration/RegistrationPanel.tsx
  app/components/modules/registration/SignUp.tsx
  app/hooks/LunchGroupContext.tsx
  app/services/firebase/admin.ts
  app/styles/custom.scss
  app/styles/main.scss
  app/styles/parts/global.scss
  app/styles/parts/layout.scss
  app/styles/parts/timepicker.scss
  app/styles/tailwind.scss
  app/types/custom.d.ts
  app/types/props.ts
  app/types/types.ts
  app/utils/guards.tsx
  package.json
  pages/_app.tsx
  tsconfig.json
  yarn.lock
Labels: bug, enhancement

#212 Create detail Views, Remove next-optimize-images
  .env example
  .gitattributes
  app/components/common/forms/EmailInput.tsx
  app/components/layouts/Layout.tsx
  app/components/modules/dashboard/DashboardPanel.tsx
  app/components/modules/dashboard/components/CreatorSubtitle.tsx
  app/components/modules/dashboard/components/LunchGroup.tsx
  app/components/modules/dashboard/components/LunchGroupButton.tsx
  app/components/modules/main/Background.tsx
  app/components/modules/main/Footer/MakerLink.tsx
  app/components/modules/main/Footer/Makers.tsx
  app/components/modules/main/Footer/Newsletter.tsx
  app/components/modules/main/Header/ActionsList/ListItemButton.tsx
  app/components/modules/main/Profile/MyGroups.tsx
  app/components/modules/main/Profile/ProfilePanel.tsx
  app/components/modules/registration/Login.tsx
  app/hooks/LunchGroupContext.tsx
  app/services/firebase/auth.ts
  app/services/firebase/firestore.ts
  app/styles/parts/global.scss
  app/types/props.ts
  app/types/types.ts
  app/utils/guards.tsx
  next.config.js
  package.json
  pages/groups/[groupId].tsx
  pages/index.tsx
  pages/profile.tsx
  tailwind.config.js
  yarn.lock
Labels: bugfix, enhancement

#229 [PR] Quick bugfix for vertical layout.
  app/components/layouts/Layout.tsx
Labels: bugfix
